#!/bin/sh -e

<<<<<<<< HEAD:debian/linux-image-5.15.0-kali3-riscv64.prerm
version=5.15.0-kali3-riscv64
========
version=5.16.0-1-powerpc64le
>>>>>>>> debian:debian/linux-image-5.16.0-1-powerpc64le.prerm
image_path=/boot/vmlinux-$version

if [ "$1" != remove ]; then
    exit 0
fi

linux-check-removal $version

if [ -d /etc/kernel/prerm.d ]; then
    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
	      --arg=$image_path /etc/kernel/prerm.d
fi

exit 0
